// Copyright OpenUSDConnect Contributors. All Rights Reserved.
//
// ============================================================================
//  AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
//  Generated by scripts/generate_unreal_protocol.py from:
//    openusdconnect/schema/messages.fbs
//    openusdconnect/schema/events.fbs
//  Regenerate after schema changes: python scripts/generate_unreal_protocol.py
// ============================================================================
//
// Wire format is decoded by hand without generated FlatBuffers code:
// every table is accessed via its vtable byte offset (VT_*), computed as
// `4 + 2*field_index`, with union types taking two slots: discriminant byte
// first, then pointer.
//
// All identifiers live in the `OUC` namespace (OpenUSDConnect) and use
// `inline constexpr` / inline functions so this header is safe to include
// from multiple .cpp files under Unreal's Unity Build.

#pragma once

#include "CoreMinimal.h"

namespace OUC
{
	inline constexpr uint32 kMaxFrameSize = 16 * 1024 * 1024;  // 16 MiB

	// ---------------------------------------------------------------------------
	// Envelope.payload union discriminants (messages.fbs)
	// ---------------------------------------------------------------------------
	inline constexpr uint8 kPayloadHello            = 1;
	inline constexpr uint8 kPayloadHelloOk          = 2;
	inline constexpr uint8 kPayloadAuthRejected     = 3;
	inline constexpr uint8 kPayloadTxn              = 4;
	inline constexpr uint8 kPayloadBroadcastEvent   = 5;
	inline constexpr uint8 kPayloadResync           = 6;
	inline constexpr uint8 kPayloadCompact          = 7;
	inline constexpr uint8 kPayloadPing             = 8;
	inline constexpr uint8 kPayloadQuit             = 9;
	inline constexpr uint8 kPayloadCreateProposal   = 10;
	inline constexpr uint8 kPayloadProposalCreated  = 11;
	inline constexpr uint8 kPayloadRateLimited      = 12;
	inline constexpr uint8 kPayloadClaimPlayback    = 13;
	inline constexpr uint8 kPayloadPlaybackClaimed  = 14;
	inline constexpr uint8 kPayloadPlaybackRejected = 15;
	inline constexpr uint8 kPayloadPlaybackControl  = 16;
	inline constexpr uint8 kPayloadPlaybackState    = 17;

	// ---------------------------------------------------------------------------
	// EventWrapper.event union discriminants (events.fbs)
	// ---------------------------------------------------------------------------
	inline constexpr uint8 kEvEnsurePrim                    = 1;
	inline constexpr uint8 kEvEnsureXformOps                = 2;
	inline constexpr uint8 kEvSetXformTrs                   = 3;
	inline constexpr uint8 kEvDeletePrim                    = 4;
	inline constexpr uint8 kEvDeactivatePrim                = 5;
	inline constexpr uint8 kEvRenamePrim                    = 6;
	inline constexpr uint8 kEvSetVisibility                 = 7;
	inline constexpr uint8 kEvSetGprimAttrs                 = 8;
	inline constexpr uint8 kEvSetReference                  = 9;
	inline constexpr uint8 kEvSetPayload                    = 10;
	inline constexpr uint8 kEvLoadPayload                   = 11;
	inline constexpr uint8 kEvUnloadPayload                 = 12;
	inline constexpr uint8 kEvSetVariantSelections          = 13;
	inline constexpr uint8 kEvSetMaterialBinding            = 14;
	inline constexpr uint8 kEvSetConnectableInput           = 15;
	inline constexpr uint8 kEvSetConnectableConnection      = 16;
	inline constexpr uint8 kEvSetStageMetadata              = 17;

	// ---------------------------------------------------------------------------
	// Vtable offsets per table
	// ---------------------------------------------------------------------------
	namespace VT
	{
		// AttrValue { value_type:AttrValueType; scalar_float:float; scalar_int:int; scalar_bool:bool; scalar_string:string; float_array:[float]; int_array:[int]; nested_json:string; stride:ubyte }
		inline constexpr uint16 AttrValue_ValueType    = 4;
		inline constexpr uint16 AttrValue_ScalarFloat  = 6;
		inline constexpr uint16 AttrValue_ScalarInt    = 8;
		inline constexpr uint16 AttrValue_ScalarBool   = 10;
		inline constexpr uint16 AttrValue_ScalarString = 12;
		inline constexpr uint16 AttrValue_FloatArray   = 14;
		inline constexpr uint16 AttrValue_IntArray     = 16;
		inline constexpr uint16 AttrValue_NestedJson   = 18;
		inline constexpr uint16 AttrValue_Stride       = 20;

		// PrimvarMeta { attr_name:string; type_name:string; interpolation:string }
		inline constexpr uint16 PrimvarMeta_AttrName      = 4;
		inline constexpr uint16 PrimvarMeta_TypeName      = 6;
		inline constexpr uint16 PrimvarMeta_Interpolation = 8;

		// AttrInterp { attr_name:string; interpolation:string }
		inline constexpr uint16 AttrInterp_AttrName      = 4;
		inline constexpr uint16 AttrInterp_Interpolation = 6;

		// NamedAttr { name:string; value:AttrValue }
		inline constexpr uint16 NamedAttr_Name  = 4;
		inline constexpr uint16 NamedAttr_Value = 6;

		// ArcEntry { asset_path:string; prim_path:string }
		inline constexpr uint16 ArcEntry_AssetPath = 4;
		inline constexpr uint16 ArcEntry_PrimPath  = 6;

		// Connection { local_attr:string; source_prim:string; source_attr:string }
		inline constexpr uint16 Connection_LocalAttr  = 4;
		inline constexpr uint16 Connection_SourcePrim = 6;
		inline constexpr uint16 Connection_SourceAttr = 8;

		// StringPair { key:string; value:string }
		inline constexpr uint16 StringPair_Key   = 4;
		inline constexpr uint16 StringPair_Value = 6;

		// ConnectableInputValue { name:string; type_name:string; value_type:ConnectableInputValueType; scalar_float:float; scalar_int:int; scalar_bool:bool; scalar_string:string; float_array:[float] }
		inline constexpr uint16 ConnectableInputValue_Name         = 4;
		inline constexpr uint16 ConnectableInputValue_TypeName     = 6;
		inline constexpr uint16 ConnectableInputValue_ValueType    = 8;
		inline constexpr uint16 ConnectableInputValue_ScalarFloat  = 10;
		inline constexpr uint16 ConnectableInputValue_ScalarInt    = 12;
		inline constexpr uint16 ConnectableInputValue_ScalarBool   = 14;
		inline constexpr uint16 ConnectableInputValue_ScalarString = 16;
		inline constexpr uint16 ConnectableInputValue_FloatArray   = 18;

		// EnsurePrim { prim:string; type_name:string; api_schemas:[string] }
		inline constexpr uint16 EnsurePrim_Prim       = 4;
		inline constexpr uint16 EnsurePrim_TypeName   = 6;
		inline constexpr uint16 EnsurePrim_ApiSchemas = 8;

		// EnsureXformOps { prim:string }
		inline constexpr uint16 EnsureXformOps_Prim = 4;

		// SetXformTrs { prim:string; fields:ubyte; t:[float]; r:[float]; s:[float]; time:double }
		inline constexpr uint16 SetXformTrs_Prim   = 4;
		inline constexpr uint16 SetXformTrs_Fields = 6;
		inline constexpr uint16 SetXformTrs_T      = 8;
		inline constexpr uint16 SetXformTrs_R      = 10;
		inline constexpr uint16 SetXformTrs_S      = 12;
		inline constexpr uint16 SetXformTrs_Time   = 14;

		// DeletePrim { prim:string }
		inline constexpr uint16 DeletePrim_Prim = 4;

		// DeactivatePrim { prim:string; active:bool }
		inline constexpr uint16 DeactivatePrim_Prim   = 4;
		inline constexpr uint16 DeactivatePrim_Active = 6;

		// RenamePrim { prim:string; new_name:string }
		inline constexpr uint16 RenamePrim_Prim    = 4;
		inline constexpr uint16 RenamePrim_NewName = 6;

		// SetVisibility { prim:string; visible:bool; time:double }
		inline constexpr uint16 SetVisibility_Prim    = 4;
		inline constexpr uint16 SetVisibility_Visible = 6;
		inline constexpr uint16 SetVisibility_Time    = 8;

		// SetGprimAttrs { prim:string; attrs:[NamedAttr]; primvar_meta:[PrimvarMeta]; attr_interp:[AttrInterp]; time:double }
		inline constexpr uint16 SetGprimAttrs_Prim        = 4;
		inline constexpr uint16 SetGprimAttrs_Attrs       = 6;
		inline constexpr uint16 SetGprimAttrs_PrimvarMeta = 8;
		inline constexpr uint16 SetGprimAttrs_AttrInterp  = 10;
		inline constexpr uint16 SetGprimAttrs_Time        = 12;

		// SetReference { prim:string; refs:[ArcEntry] }
		inline constexpr uint16 SetReference_Prim = 4;
		inline constexpr uint16 SetReference_Refs = 6;

		// SetPayload { prim:string; payloads:[ArcEntry] }
		inline constexpr uint16 SetPayload_Prim     = 4;
		inline constexpr uint16 SetPayload_Payloads = 6;

		// LoadPayload { prim:string }
		inline constexpr uint16 LoadPayload_Prim = 4;

		// UnloadPayload { prim:string }
		inline constexpr uint16 UnloadPayload_Prim = 4;

		// SetVariantSelections { prim:string; selections:[StringPair] }
		inline constexpr uint16 SetVariantSelections_Prim       = 4;
		inline constexpr uint16 SetVariantSelections_Selections = 6;

		// SetMaterialBinding { prim:string; material_path:string }
		inline constexpr uint16 SetMaterialBinding_Prim         = 4;
		inline constexpr uint16 SetMaterialBinding_MaterialPath = 6;

		// SetConnectableInput { prim:string; info_id:string; inputs:[ConnectableInputValue]; time:double }
		inline constexpr uint16 SetConnectableInput_Prim   = 4;
		inline constexpr uint16 SetConnectableInput_InfoId = 6;
		inline constexpr uint16 SetConnectableInput_Inputs = 8;
		inline constexpr uint16 SetConnectableInput_Time   = 10;

		// SetConnectableConnection { prim:string; connections:[Connection]; disconnections:[string] }
		inline constexpr uint16 SetConnectableConnection_Prim           = 4;
		inline constexpr uint16 SetConnectableConnection_Connections    = 6;
		inline constexpr uint16 SetConnectableConnection_Disconnections = 8;

		// SetStageMetadata { timeCodesPerSecond:double; framesPerSecond:double; startTimeCode:double; endTimeCode:double; metersPerUnit:double; upAxis:string }
		inline constexpr uint16 SetStageMetadata_TimeCodesPerSecond = 4;
		inline constexpr uint16 SetStageMetadata_FramesPerSecond    = 6;
		inline constexpr uint16 SetStageMetadata_StartTimeCode      = 8;
		inline constexpr uint16 SetStageMetadata_EndTimeCode        = 10;
		inline constexpr uint16 SetStageMetadata_MetersPerUnit      = 12;
		inline constexpr uint16 SetStageMetadata_UpAxis             = 14;

		// EventWrapper { event:EventPayload }
		inline constexpr uint16 EventWrapper_EventType = 4;
		inline constexpr uint16 EventWrapper_Event     = 6;

		// Hello { role:string; protocol_version:int; sync_from:int; client_id:string; origin:string; department:string; token:string }
		inline constexpr uint16 Hello_Role            = 4;
		inline constexpr uint16 Hello_ProtocolVersion = 6;
		inline constexpr uint16 Hello_SyncFrom        = 8;
		inline constexpr uint16 Hello_ClientId        = 10;
		inline constexpr uint16 Hello_Origin          = 12;
		inline constexpr uint16 Hello_Department      = 14;
		inline constexpr uint16 Hello_Token           = 16;

		// HelloOk { token:string; stage_metadata:SetStageMetadata }
		inline constexpr uint16 HelloOk_Token         = 4;
		inline constexpr uint16 HelloOk_StageMetadata = 6;

		// AuthRejected { reason:string }
		inline constexpr uint16 AuthRejected_Reason = 4;

		// Txn { client_id:string; events:[EventWrapper]; proposal_id:string }
		inline constexpr uint16 Txn_ClientId   = 4;
		inline constexpr uint16 Txn_Events     = 6;
		inline constexpr uint16 Txn_ProposalId = 8;

		// BroadcastEvent { seq:int; event:EventWrapper; origin:string; client_id:string; client:string }
		inline constexpr uint16 BroadcastEvent_Seq      = 4;
		inline constexpr uint16 BroadcastEvent_Event    = 6;
		inline constexpr uint16 BroadcastEvent_Origin   = 8;
		inline constexpr uint16 BroadcastEvent_ClientId = 10;
		inline constexpr uint16 BroadcastEvent_Client   = 12;

		// CreateProposal { target_department:string; events:[EventWrapper]; description:string }
		inline constexpr uint16 CreateProposal_TargetDepartment = 4;
		inline constexpr uint16 CreateProposal_Events           = 6;
		inline constexpr uint16 CreateProposal_Description      = 8;

		// ProposalCreated { proposal_id:string }
		inline constexpr uint16 ProposalCreated_ProposalId = 4;

		// RateLimited { retry_after:float }
		inline constexpr uint16 RateLimited_RetryAfter = 4;

		// ClaimPlayback { client_id:string; time:double }
		inline constexpr uint16 ClaimPlayback_ClientId = 4;
		inline constexpr uint16 ClaimPlayback_Time     = 6;

		// PlaybackClaimed { leader_client_id:string }
		inline constexpr uint16 PlaybackClaimed_LeaderClientId = 4;

		// PlaybackRejected { reason:string; current_leader_client_id:string }
		inline constexpr uint16 PlaybackRejected_Reason                = 4;
		inline constexpr uint16 PlaybackRejected_CurrentLeaderClientId = 6;

		// PlaybackControl { action:string; time:double; rate:double }
		inline constexpr uint16 PlaybackControl_Action = 4;
		inline constexpr uint16 PlaybackControl_Time   = 6;
		inline constexpr uint16 PlaybackControl_Rate   = 8;

		// PlaybackState { time:double; playing:bool; rate:double; leader_client_id:string }
		inline constexpr uint16 PlaybackState_Time           = 4;
		inline constexpr uint16 PlaybackState_Playing        = 6;
		inline constexpr uint16 PlaybackState_Rate           = 8;
		inline constexpr uint16 PlaybackState_LeaderClientId = 10;

		// Envelope { payload:Payload; schema_version:uint16 }
		inline constexpr uint16 Envelope_PayloadType   = 4;
		inline constexpr uint16 Envelope_Payload       = 6;
		inline constexpr uint16 Envelope_SchemaVersion = 8;
	} // namespace VT

	// ---------------------------------------------------------------------------
	// FlatBuffers raw-read helpers (header-only, inline).
	// Schema-independent — not regenerated; safe to edit.
	// ---------------------------------------------------------------------------
	namespace FB
	{
		// Read a little-endian scalar of type T from byte pointer P.
		// FlatBuffers stores all data little-endian; x86/ARM64 are LE so memcpy works.
		template<typename T>
		FORCEINLINE T ReadLE(const uint8* P)
		{
			T V;
			FMemory::Memcpy(&V, P, sizeof(T));
			return V;
		}

		// Returns the byte offset of field VtOff in Table's vtable (or 0 if field absent).
		FORCEINLINE uint16 FieldOff(const uint8* Table, uint16 VtOff)
		{
			const int32  Soff   = ReadLE<int32>(Table);
			const uint8* Vtable = Table - Soff;
			const uint16 VtSize = ReadLE<uint16>(Vtable);
			if (VtOff >= VtSize) return 0;
			return ReadLE<uint16>(Vtable + VtOff);
		}

		// True iff the field is present in the table's vtable.
		FORCEINLINE bool HasField(const uint8* Table, uint16 VtOff)
		{
			return FieldOff(Table, VtOff) != 0;
		}

		// Read a scalar field; returns Def if field is absent.
		template<typename T>
		FORCEINLINE T GetField(const uint8* Table, uint16 VtOff, T Def = T{})
		{
			const uint16 Off = FieldOff(Table, VtOff);
			return Off ? ReadLE<T>(Table + Off) : Def;
		}

		// Dereference an offset field (string / table / vector pointer).
		// FlatBuffers offsets are relative to the position of the offset itself.
		FORCEINLINE const uint8* GetPtr(const uint8* Table, uint16 VtOff)
		{
			const uint16 Off = FieldOff(Table, VtOff);
			if (!Off) return nullptr;
			const uint8* FldPtr = Table + Off;
			const uint32 Ref    = ReadLE<uint32>(FldPtr);
			return FldPtr + Ref;
		}

		// Decode a FlatBuffers string field into an FString (UTF-8 → TCHAR).
		FORCEINLINE FString GetStr(const uint8* Table, uint16 VtOff)
		{
			const uint8* Str = GetPtr(Table, VtOff);
			if (!Str) return {};
			const uint32 Len = ReadLE<uint32>(Str);
			return FString(static_cast<int32>(Len),
			               reinterpret_cast<const ANSICHAR*>(Str + 4));
		}

		// Read a [float] vector field into a TArray<float>.
		FORCEINLINE TArray<float> GetFloatVec(const uint8* Table, uint16 VtOff)
		{
			const uint8* Vec = GetPtr(Table, VtOff);
			if (!Vec) return {};
			const uint32 Size = ReadLE<uint32>(Vec);
			TArray<float> Out;
			Out.SetNumUninitialized(static_cast<int32>(Size));
			FMemory::Memcpy(Out.GetData(), Vec + 4, Size * sizeof(float));
			return Out;
		}

		// Number of elements in a vector field (0 if absent).
		FORCEINLINE uint32 GetVecSize(const uint8* Table, uint16 VtOff)
		{
			const uint8* Vec = GetPtr(Table, VtOff);
			return Vec ? ReadLE<uint32>(Vec) : 0;
		}

		// Get the ith element of a vector-of-offsets (vector of tables/strings).
		FORCEINLINE const uint8* GetVecElem(const uint8* Table, uint16 VtOff, uint32 Index)
		{
			const uint8* Vec = GetPtr(Table, VtOff);
			if (!Vec) return nullptr;
			const uint8* ElemPtr = Vec + 4 + Index * 4;
			const uint32 Off     = ReadLE<uint32>(ElemPtr);
			return ElemPtr + Off;
		}

		// Convenience: read the ith string from a [string] vector field.
		FORCEINLINE FString GetStrVecElem(const uint8* Table, uint16 VtOff, uint32 Index)
		{
			const uint8* Str = GetVecElem(Table, VtOff, Index);
			if (!Str) return {};
			const uint32 Len = ReadLE<uint32>(Str);
			return FString(static_cast<int32>(Len),
			               reinterpret_cast<const ANSICHAR*>(Str + 4));
		}

		// Decode the root table pointer of an Envelope from raw frame bytes.
		FORCEINLINE const uint8* GetRoot(const TArray<uint8>& Buf)
		{
			if (Buf.Num() < 4) return nullptr;
			const uint32 Off = ReadLE<uint32>(Buf.GetData());
			return Buf.GetData() + Off;
		}
	} // namespace FB

} // namespace OUC
